# Generated by Django 4.2.7 on 2024-06-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('passion', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=250, unique=True)),
                ('profile_picture', models.FileField(upload_to='profile')),
                ('dateJoin', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
