# Generated by Django 4.2.7 on 2024-06-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_activate_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
