# Generated by Django 4.2.7 on 2024-06-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
