# Generated by Django 4.2.7 on 2024-06-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
