# Generated by Django 4.2.7 on 2024-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_author_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final_price',
            field=models.IntegerField(null=True),
        ),
    ]
