# Generated by Django 4.2.7 on 2024-01-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='final_price',
        ),
    ]
