# Generated by Django 4.2.7 on 2024-06-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_product_cartitemmodel_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartItemModel',
        ),
        migrations.DeleteModel(
            name='cartModel',
        ),
    ]
